update build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,36 +1,140 @@
-name: build
+
+# Copyright © 2017-2024 Dominic Heutelbeck (dominic@heutelbeck.com)
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+name: Testing and Publishing
 
 on:
   workflow_dispatch:
   push:
-    branches: [main]
-  repository_dispatch:
-    branches: [main]
-  
+    branches:
+      - '**'
+    paths-ignore:
+      - '.github/workflows/**'
+      - '!.github/workflows/build.yml'
+      - '**.md'
+  pull_request:
+    paths-ignore:
+      - '.github/workflows/**'
+      - '!.github/workflows/build.yml'
+      - '**.md'
+
+permissions:
+  contents: read
+
 jobs:
   build:
+    strategy:
+      matrix:
+        java: [ '17']
+        os: [ubuntu-latest]
+      fail-fast: false
+    name: Build (JDK ${{ matrix.java }} on ${{ matrix.os }})
+    runs-on: ${{ matrix.os }}
+    permissions:
+      actions: write # for Mattraks/delete-workflow-runs
+      checks: write # for scacap/action-surefire-report to publish result as PR check
+    timeout-minutes: 45
 
-    runs-on: ubuntu-latest
- 
     steps:
+    - name: Harden Runner
+      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
+      with:
+        egress-policy: audit
+
     - name: Check out
       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       with:
         lfs: true
         fetch-depth: 0
-        
-    - name: Set up JDK 17
+
+    - name: Set up JDK ${{ matrix.java }}
       uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
       with:
-        distribution: 'adopt'
-        java-version: 17
+        distribution: temurin
+        java-version: ${{ matrix.java }}
         cache: 'maven'
-       
-    - name: Build with Maven (JUnit, JaCoCo, Sonar) 
-      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar -Dsonar.host.url=https://sonar.ftk.de -Dsonar.login=${{ secrets.SONAR_TOKEN }} -P production
 
-    - name: Build SAPL Server CE Docker image
+    - name: Run Tests
+      # Tests: spotbugs
+      run: mvn -U -B verify -fae spotbugs:spotbugs -Pspotbugs -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
+
+    - name: Cache Sonar Packages
+      if: ${{ !github.event.pull_request.head.repo.fork && (matrix.os == 'ubuntu-latest') && (matrix.java == '17') && (github.actor != 'dependabot[bot]') }}
+      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
+      with:
+        path: ~/.sonar/cache
+        key: ${{ runner.os }}-sonar
+        restore-keys: ${{ runner.os }}-sonar
+
+    - name: Run SonarCloud Analysis
+      # Not allowed for PRs from forks and from Dependabot. Secrets are not accessible
+      # (see: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544).
+      if: ${{ !github.event.pull_request.head.repo.fork && (github.actor != 'dependabot[bot]') }}
+      env:
+        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
+      run: >
+        mvn -B sonar:sonar
+        -'Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
+        -Dsonar.organization=heutelbeck
+        -Dsonar.host.url=https://sonarcloud.io
+        -Dsonar.projectKey=heutelbeck_sapl-server
+        -Dsonar.java.spotbugs.reportPaths=target/spotbugsXml.xml
+        -Dsonar.qualitygate.wait=true
+
+    - name: Save PR Number # needed for subsequent SonarCloud workflow for PRs from fork
+      if: ${{ github.event.pull_request.head.repo.fork }}
+      run: echo "${{ github.event.number }}" > pr_data.txt
+
+    - name: Upload Artifact # needed for subsequent SonarCloud workflow for PRs from fork
+      if: ${{ github.event.pull_request.head.repo.fork }}
+      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
+      with:
+        name: pr_build
+        path: |
+          **/src
+          **/target/spotbugsXml.xml
+          **/target/classes
+          **/target/test-classes
+          **/target/site/jacoco/jacoco.xml
+          **/pom.xml
+          pom.xml
+          pr_data.txt
+          .git
+        retention-days: 1
+
+    - name: Build and Publish SAPL Server CE Docker Image
+      if: ${{ github.ref == 'refs/heads/master' }}
       run: mvn -B clean spring-boot:build-image -pl sapl-server-ce -P docker,production -DskipTests -Dspring-boot.build-image.publish=true -Ddocker.credentials.username=${{ secrets.GHUB_USERNAME }} -Ddocker.credentials.password=${{ secrets.GHUB_ACCESS_TOKEN }}
-                 
-    - name: Clean up local repository before caching
-      run: rm -rf /.m2/repository/io/sapl
+
+# This step an be activated as soon as unit tests exist.
+#    - name: Publish Test Report
+#      # Not allowed for PRs from forks and from Dependabot. The GITHUB_TOKEN stays read-only
+#      # (see: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544).
+#      if: ${{ (success() || failure()) && !github.event.pull_request.head.repo.fork && (github.actor != 'dependabot[bot]') }}
+#      uses: scacap/action-surefire-report@a2911bd1a4412ec18dde2d93b1758b3e56d2a880 # v1.8.0
+
+    - name: Delete Workflow Runs
+      # Not allowed for PRs from forks and from Dependabot. The GITHUB_TOKEN stays read-only
+      # (see: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544).
+      if: ${{ !github.event.pull_request.head.repo.fork && (github.actor != 'dependabot[bot]') }}
+      uses: Mattraks/delete-workflow-runs@39f0bbed25d76b34de5594dceab824811479e5de # v2.0.6
+      with:
+        token: ${{ github.token }}
+        repository: ${{ github.repository }}
+        retain_days: 1
+        keep_minimum_runs: 6
+
+    - name: Clean up Local Repository before Caching
+      run: rm -rf ~/.m2/repository/io/sapl
